
FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /usr/share/nginx/html/ayudantias
COPY dist/ /usr/share/nginx/html/ayudantias/

COPY README.md /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
