# Generated by Django 5.0.4 on 2024-07-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_create_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Promedio',
            field=models.FloatField(default=0.0),
        ),
    ]
